### ISSUE TITLE
Why is mandatory to have scss filename with 'module' keyword

### ISSUE THREAD

**Issue by aagamdoshi** [huybn5776/liu-online-ime#1]
I tried to refer your solution and its perfect but had one query regarding the naming convention why it has modules and if I change it it stops compiling.
I figured out for scss files but couldn't find for tsx files?

Also on running npm run build it is giving eslint error

> " Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
> The file does not match your project config: build\assets\vendor.b10eed20.js.
> The file must be included in at least one of the projects provided"

**Comment by huybn5776** [comment]
[CSS Module](https://vitejs.dev/guide/features.html#css-modules), in practice will let it's file name end with .module, and the build tool may treat it as and css module to compile.

For the eslint error, it because the file under 'build' folder is not considered to lint. You may ignore this error, or add it to `tsconfig -> include` array if necessary.

**Comment by aagamdoshi** [comment]
![image](https://user-images.githubusercontent.com/13047898/119090387-31fcab00-ba29-11eb-91a1-8dd9ea5156e1.png)
Without this the build is not getting succeded, tried to import build in tsconfig, but thats giving infinite problems.

Any way to resolve this error so that build is succeded

**Comment by huybn5776** [comment]
My fault, should not eslint whole project on build, I have [updated package.json](https://github.com/huybn5776/liu-online-ime/commit/6ac2f8bdbc7262c3957e0e543680deb539476cbb) to resolve this.
